Repository INDAPlus20/sahlest-emilsjol-nodelius-project, pull requests merged in 2021-05, with the labels that each got.

#34 Convenience/27 start backend frontend one command
  go-backend/Handlers.go
  go-backend/Message.go
  user-application/README.md
  user-application/package.json
  user-application/server.bat
Labels: enhancement

#45 Enhancement/36 backend audio handling
  go-backend/AudioData.go
  go-backend/Handlers.go
  go-backend/Message.go
  go-backend/Routes.go
  go-backend/fft.go
  user-application/src/App.js
  user-application/src/components/AudioAnalyser/AudioListener.js
  user-application/src/components/AudioAnalyser/AudioVisualiser.js
  user-application/src/components/AudioAnalyser/BackendAudioHandler.js
  user-application/src/components/AudioAnalyser/FFT.js
  user-application/src/components/AudioAnalyser/FrontendAudioHandler.js
Labels: enhancement

#50 Lade till instruktioner för Linux, Mac, Windows
  README.md
Labels: documentation

#48 Ändrade så att sidan refreshas när man byter flik
  user-application/src/components/UI/Navbar.js
Labels: bug

#51 Visualiser improved
  go-backend/Handlers.go
  user-application/src/components/AudioAnalyser/Audio.css
  user-application/src/components/AudioAnalyser/AudioListener.js
  user-application/src/components/AudioAnalyser/AudioVisualiser.js
  user-application/src/components/AudioAnalyser/FrontendAudioHandler.js
  user-application/src/components/Pages/AudioRecording.js
Labels: enhancement

#52 Chatbot fick mening
  go-backend/Handlers.go
  go-backend/Routes.go
  go-backend/StringData.go
  go-backend/toRovarsprak.go
  user-application/src/components/AudioAnalyser/FrontendAudioHandler.js
  user-application/src/components/Pages/Chatbot.js
Labels: feature
